name: Deploy

# Run action on release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Run Deployment Script
        run: scripts/deploy.sh